### ISSUE TITLE
[FE] 라우팅 설정

### ISSUE THREAD

**Issue by pds0309** [Pinterest-Clone-Group/frontend#1]
<br>

[피그마 와이어 프레임 및 디자인](https://www.figma.com/file/38dehNIuXVt9FzSEuSmtaa/Pinterest-clone?node-id=62%3A2&t=rJ5tGqAIpqNU68ah-1) 을 참고해

페이지 라우팅 설정

**Comment by ptg0811** [comment]
네 확인했습니다

**Comment by ptg0811** [comment]
- [x] index.jsx
- [x] App.jsx
- [x] Layout.jsx
- [x] Router.jsx
- [x] Home.jsx

- 추후 수정 및 추가 예정
